export const wellnessTips = [
  "Stay hydrated! Drink at least 8 glasses of water a day.",
  "Aim for 7-9 hours of sleep each night for optimal recovery.",
  "Incorporate strength training 2-3 times per week to build muscle.",
  "Take short walks during work breaks to improve circulation.",
  "Eat a balanced diet with plenty of fruits and vegetables.",
  "Practice deep breathing exercises to reduce stress.",
  "Set realistic fitness goals and track your progress.",
  "Include flexibility exercises like yoga in your routine.",
  "Listen to your body and rest when needed.",
  "Fuel your workouts with proper nutrition before and after.",
  "Maintain good posture to prevent injuries.",
  "Try new exercises to keep your routine exciting.",
  "Consistency is key - small daily efforts add up.",
  "Warm up before workouts and cool down after.",
  "Stay motivated by finding a workout buddy.",
  "Track your meals to ensure balanced nutrition.",
  "Incorporate cardio for heart health.",
  "Strengthen your core for better stability.",
  "Get sunlight exposure for vitamin D.",
  "Practice mindfulness to enhance mental well-being.",
];